### PR TITLE
update copyright for all lab

### PR DESCRIPTION
**Pull request by junghans**
To Do, add contract numbers for:

- [x] LANL
- [x] ORNL
- [x] LLNL
- [x] PPPL
- [x] SNL

### CODE REVIEW

**Comment by sslattery** [comment]
Is LANL requiring this?

**Comment by junghans** [comment]
@tcgermann and @FCI-LANL know more, but the short answer is yes.

**Comment by junghans** [comment]
I should add the code number in the readme.

**Comment by guangyechen** [comment]
@junghans Does it mean that it has passed LANL approval?

**Comment by tcgermann** [comment]
If LANL requires this, then we should also add copyright assertion lines for all contributing institutions (ORNL, PPPL, LLNL, SNL, ...), as well as their accompanying paragraph.  If this is really what LANL wants/requires, we should use a separate LICENSE file rather than repeat the same 100 lines in each file.  Or is this the model we should follow: https://github.com/E3SM-Project/E3SM/blob/master/LICENSE

**Comment by sslattery** [comment]
I agree with @tcgermann - we want the optics here to be that this is a team effort.

**Comment by junghans** [comment]
Ok, I think we can do that. Keep the individual file under Cabana auhors and define the authors in the license file. However, we still need to keep the government clause in license file.

Does that sound reasonable? 

@FCI-LANL any comments?

**Comment by FCI-LANL** [comment]
No problem with listing the other authoring organizations and labs. Having separate license file to include the full authors, BSD text, and gov use language is fine.
Thanks!

Kaelyn

**Comment by junghans** [comment]
@tcgermann @sslattery better?

**Comment by junghans** [comment]
`git log | grep Author | sed 's/.*@//' | sort -u` is what I did, no contribution from SNL yet.

**Comment by sslattery** [comment]
Fair enough

**Comment by junghans** [comment]
Added anyhow, now ready to merge!

@tcgermann please review.

**Comment by tcgermann** [comment]
Looks better, can we go ahead and modify the paragraph as Kaelyn suggests below (we'd need to get the contractor and contract # for each lab):

> Assuming the other labs have gone through the assertion process, the language below can be revised to:
>  
> © (or copyright) 2019. Triad National Security, LLC. All rights reserved.
> © (or copyright) (year of assertion). Lab #2 Contractor/Operator. All rights reserved.
> © (or copyright) (year of assertion). Lab #3 Contractor/Operator. All rights reserved.
>  
> This program was produced under U.S. Government contract 89233218CNA000001 for Los Alamos National Laboratory (LANL), U.S. Government Contract ####### for Lab #2, and U.S. Government Contract ####### for Lab #3…

**Comment by junghans** [comment]
@tcgermann good point!

@sslattery, can you add the data for ORNL?
@streeve, can you add the data for LLNL?
@stanmoore1, can you add the data for SNL?

**Comment by sslattery** [comment]
@ascheinb Can you add PPPL info as well?

**Comment by streeve** [comment]
For LLNL: 

This program was produced under [...] U.S. Government Contract DE-AC52-07NA27344 for Lawrence Livermore National Laboratory (LLNL) [...]

Our plan is to include the auspices statement, but otherwise contribute to the open source project without an LLNL specific copyright

**Comment by ascheinb** [comment]
I am asking PPPL what our statement should be. They want to know if it's open source - just to be clear, that's a yes, right?

**Comment by sslattery** [comment]
Yes - open source with a BSD 3-clause license

**Comment by sslattery** [comment]
ORNL Contractor: UT-Battelle
ORNL Contract #: DE-AC05- 00OR22725

**Comment by stanmoore1** [comment]
Sandia Contractor: NTESS
Sandia Contract #: DE-NA-0003525
I will ask around about copyright assertion.

**Comment by sslattery** [comment]
@ascheinb any update on the PPPL language?

**Comment by ascheinb** [comment]
Yes, Stephane and I received this verdict:

> We have consulted with Princeton's OGC and the way you have listed your shared rights as part of the development group is fine, legally, but the following pieces of advice were also passed on:
> 
>     The license should list the authors under the “Copyright 2018-2019 the Cabana authors”  line for clarity
>     There is a variation of the BSD 3-Clause license that adds:  “NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE.”  See BSD 3-Clause Clear License (https://choosealicense.com/licenses/bsd-3-clause-clear/).  This may provide additional protection if PPPL (or DOE, or any of the other national lab collaborators) have patents, or anticipate filing patents, on inventions related to this code, avoiding modifications of the code that could infringe PPPL/DOE/etc. patents. However, a potential downside to the BSD 3-Clause Clear License is that others may be reluctant to use or build on the code if they are worried about potentially infringing a related patent.

**Comment by sslattery** [comment]
@junghans what's the best way to incorporate the PPPL comments?

**Comment by junghans** [comment]
@sslattery I hoped you would know ;-)

**Comment by ascheinb** [comment]
Yeah I wasn't sure what to do with it either. But they do say the existing version is "fine" so I guess we don't have to do anything. :)

**Comment by sslattery** [comment]
I say then that we leave as is based on PPPL legal response. If we need to change in the future then this PR can serve as a reference to PPPL's suggestion after it is closed.

**Pull request merged**
