### PR TITLE
Do not attempt to pull a newer version of image in CUDA CI build

### PR DESCRIPTION
**Pull request by dalg24**
Docker Hub started enforcing rate limits and we started having issues on our Jenkins CI server
```
You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limits.
```

### CODE REVIEW

**Review by sslattery — APPROVED** [review]

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Pull request merged**
