### PR TITLE
Enable CI through Travis

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
Yes

**Comment by sslattery** [comment]
Will this also run the unit tests? Curious as to if we can add `ctest` to the script. Also is there a way to verify that this works? I'm assuming this preliminary setup will run on some free GitHub CI.

**Comment by junghans** [comment]
You can do everything, you just `script:` block.

**Comment by junghans** [comment]
Ok, it runs the tests now and add coverage reporting.

**Pull request merged**
