### PR TITLE
Switch Intel CI runs to icpx

### PR DESCRIPTION
**Pull request by streeve**
Warnings in the log output

### CODE REVIEW

**Comment by streeve** [comment]
@junghans not sure if this is a good idea, but I thought it was worth a try especially with the persistent Intel CI failures - I think it's complaining about `-g` instead of `-g0`

**Comment by junghans** [comment]
`icpc` is obsolete, so `icpx` is the way to go!

**Comment by streeve** [comment]
```
icpx: error: Note that use of '-g' without any optimization-level option will turn off most compiler optimizations similar to use of '-O0' [-Werror,-Wdebug-disables-optimization]
```

Is there a simple way to get CMake to set `-g0` or ignore this?

**Comment by junghans** [comment]
@streeve now we are at:
```
25/99 Test #25: Cajita_Splines_test_SERIAL ..........................***Failed    0.01 sec
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from cajita_splines
[ RUN      ] cajita_splines.zero_spline_test
[       OK ] cajita_splines.zero_spline_test (0 ms)
[ RUN      ] cajita_splines.linear_spline_test
[       OK ] cajita_splines.linear_spline_test (0 ms)
[ RUN      ] cajita_splines.quadratic_spline_test
[       OK ] cajita_splines.quadratic_spline_test (0 ms)
[ RUN      ] cajita_splines.cubic_spline_test
/__w/Cabana/Cabana/cajita/unit_test/tstSplines.hpp:228: Failure
Expected equality of these values:
  sum
    Which is: 0.99999999999999845
  1.0
    Which is: 1
[  FAILED  ] cajita_splines.cubic_spline_test (0 ms)
[----------] 4 tests from cajita_splines (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] cajita_splines.cubic_spline_test

 1 FAILED TEST
```

**Comment by streeve** [comment]
HIP failure is unrelated

**Comment by streeve** [comment]
@abisner can you review?

**Review by abisner — APPROVED** [review]

**Pull request merged**
