### PR TITLE
Add CI run with Kokkos bounds checking

### PR DESCRIPTION
**Pull request by streeve**

### CODE REVIEW

**Comment by streeve** [comment]
@kwitaechong I fixed the out of bounds for the structured solver, but now one of the 10 tests fails - can you take a look at that?

**Review by junghans — APPROVED** [review]

**Comment by kwitaechong** [comment]
> @kwitaechong I fixed the out of bounds for the structured solver, but now one of the 10 tests fails - can you take a look at that?

Looks good!

**Comment by streeve** [comment]
I still see local failures. Can you run locally @kwitaechong?

**Comment by streeve** [comment]
@sslattery just looking for a quick check on how I updated the solver halos here

**Comment by kwitaechong** [comment]
> I still see local failures. Can you run locally @kwitaechong?

Yes, I run locally and all passed

**Pull request merged**
