### PR TITLE
.ecp-gitlab-ci.yml: bump kokkos version

### PR DESCRIPTION
**Pull request by junghans**
Fix up of #217

### CODE REVIEW

**Comment by dalg24** [comment]
@junghans does that still run?  If so where does it post the reports?

**Comment by junghans** [comment]
It worked until you broke it ;-)

**Comment by junghans** [comment]
Let's wait for https://code.ornl.gov/ecpcitest/ecp-copa/cabana/pipelines/98692

**Comment by junghans** [comment]
ECP CI passed.

**Pull request merged**
