### PR TITLE
CI: use kokkos 3.0.00

### PR DESCRIPTION
**Pull request by junghans**
- [x] Travis
- [x] Gitlab
- [x] Jenkins
- [x] ECP CI: https://code.ornl.gov/ecpcitest/ecp-copa/cabana/pipelines/91475

### CODE REVIEW

**Comment by junghans** [comment]
@dalg24 please check for Jenkins.

**Comment by dalg24** [comment]
Jenkins is already using the 3.0 release
https://github.com/ECP-copa/Cabana/blob/0f81bea92d2feb149c4b0acb782f54a34930d597/scripts/jenkins/Dockerfile#L53

**Comment by dalg24** [comment]
> Are then Jenkins changes already done? Or is it in our Docker image I guess?

Yes.  See the cross reference to the Dockerfile

**Comment by sslattery** [comment]
> > Are then Jenkins changes already done? Or is it in our Docker image I guess?
> 
> Yes. See the cross reference to the Dockerfile

Oh yeah OK sorry - ready to merge?

**Pull request merged**
