### PR TITLE
Set max numprocs

### PR DESCRIPTION
**Pull request by streeve**
Set `MPIEXEC_MAX_NUMPROCS` for jenkins. 

Set unit test max procs and threads in the same way for both Cabana and Cajita

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by streeve** [comment]
@dalg24 just wanted to check if 2 ranks is most reasonable for jenkins

**Comment by dalg24** [comment]
> @dalg24 just wanted to check if 2 ranks is most reasonable for jenkins

Machines have all at least 8 cores but a single GPU.

**Comment by streeve** [comment]
@sslattery do you think we should stick with 2 ranks, or just 1 for the GPU?

**Comment by sslattery** [comment]
> @sslattery do you think we should stick with 2 ranks, or just 1 for the GPU?

Let's just do 1 rank if there is only 1 GPU. Our current programming model assumes a single MPI rank per GPU. We will still get some MPI tests because of problems with periodic boundaries.

**Review by sslattery — APPROVED** [review]

**Pull request merged**
