### PR TITLE
Run SYCL Cajita tests

### PR DESCRIPTION
**Pull request by streeve**

### CODE REVIEW

**Comment by streeve** [comment]
Just checking if the recent changes fixed anything with CUDA SYCL - still failing on the same Cajita tests

**Comment by streeve** [comment]
We can close this or leave it open to remind us that these fail

**Review by sslattery — APPROVED** [review]

**Comment by sslattery** [comment]
> We can close this or leave it open to remind us that these fail

I'm OK with leaving open because we should attempt to fix a lot of the warnings in here at least if not also the errors.

**Comment by streeve** [comment]
@steverangel here's some of the errors we only get with CUDA SYCL (as far as I can tell): https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Cabana/detail/PR-479/2/pipeline/14

**Comment by masterleinad** [comment]
There are known issues with building in `Debug` mode for SYCL+CUDA. Building in `Release` mode should work much better.

**Comment by masterleinad** [comment]
Also, feel free to reach out to me for `SYCL` issues.

**Comment by masterleinad** [comment]
See https://github.com/intel/llvm/issues/5980.

**Comment by streeve** [comment]
Thanks for the help here!

**Pull request merged**
