### PR TITLE
Require Kokkos 3.2

### PR DESCRIPTION
**Pull request by streeve**
Also re-enable HIP with `VerletList` hierarchical reductions

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
Retest this please

**Comment by sslattery** [comment]
Do we also need to update this? https://github.com/ECP-copa/Cabana/blob/a502acf1c37932dcda52248f33d2b12f90b934f2/CMakeLists.txt#L33

**Review by sslattery — APPROVED** [review]
Question on the required CMake version of Kokkos

**Comment by streeve** [comment]
Retest this please

**Pull request merged**
