### PR TITLE
Shared memory atomic communication plan

### PR DESCRIPTION
**Pull request by streeve**
Note that above 64 neighbor ranks, this reverts to the original version with global memory

### CODE REVIEW

**Comment by streeve** [comment]
This is the overall timings for creation (migrate/gather are not affected with noise at a few percent change). No discernible changes at 10k particles

Overall timing comparisons, 1M particles with fraction communicated ( 0.0001, 0.001, 0.01, 0.10,  0.25,  0.5):
```
Test 			Prev(ms) 	New(ms) 	Speedup
cuda_cuda_distributor_fast_create  	 2.78   	 1.88   	 1.48
cuda_cuda_distributor_fast_create  	 2.51   	 1.84   	 1.36
cuda_cuda_distributor_fast_create  	 2.51   	 1.84   	 1.36
cuda_cuda_distributor_fast_create  	 2.52   	 1.81   	 1.39
cuda_cuda_distributor_fast_create  	 2.53   	 1.84   	 1.38
cuda_cuda_distributor_fast_create  	 2.83   	 2   	 1.42
cuda_cuda_distributor_general_create  	 2.65   	 1.87   	 1.42
cuda_cuda_distributor_general_create  	 2.5   	 1.88   	 1.33
cuda_cuda_distributor_general_create  	 2.49   	 1.88   	 1.33
cuda_cuda_distributor_general_create  	 2.56   	 1.82   	 1.41
cuda_cuda_distributor_general_create  	 2.5   	 1.89   	 1.33
cuda_cuda_distributor_general_create  	 2.48   	 1.84   	 1.35
cuda_cuda_halo_fast_create  	 0.739   	 0.732   	 1.01
cuda_cuda_halo_fast_create  	 0.697   	 0.709   	 0.984
cuda_cuda_halo_fast_create  	 0.698   	 0.705   	 0.99
cuda_cuda_halo_fast_create  	 1.13   	 1.1   	 1.03
cuda_cuda_halo_fast_create  	 1.78   	 1.67   	 1.06
cuda_cuda_halo_fast_create  	 2.01   	 1.72   	 1.17
cuda_cuda_halo_general_create  	 0.727   	 0.714   	 1.02
cuda_cuda_halo_general_create  	 0.686   	 0.696   	 0.986
cuda_cuda_halo_general_create  	 0.688   	 0.696   	 0.989
cuda_cuda_halo_general_create  	 0.761   	 0.711   	 1.07
cuda_cuda_halo_general_create  	 1.77   	 1.69   	 1.05
cuda_cuda_halo_general_create  	 2.02   	 1.76   	 1.15
```

Overall timing comparisons, 100k particles with fraction communicated ( 0.0001, 0.001, 0.01, 0.10,  0.25,  0.5):
```
Test 			Prev(ms) 	New(ms) 	Speedup
cuda_cuda_distributor_fast_create  	 1.19   	 1.17   	 1.02
cuda_cuda_distributor_fast_create  	 1.14   	 1.13   	 1.01
cuda_cuda_distributor_fast_create  	 1.14   	 1.14   	 0.998
cuda_cuda_distributor_fast_create  	 1.18   	 1.11   	 1.06
cuda_cuda_distributor_fast_create  	 1.14   	 1.11   	 1.03
cuda_cuda_distributor_fast_create  	 1.19   	 1.12   	 1.06
cuda_cuda_distributor_general_create  	 0.78   	 0.78   	 0.999
cuda_cuda_distributor_general_create  	 0.765   	 0.756   	 1.01
cuda_cuda_distributor_general_create  	 0.771   	 0.74   	 1.04
cuda_cuda_distributor_general_create  	 0.778   	 0.743   	 1.05
cuda_cuda_distributor_general_create  	 0.772   	 0.736   	 1.05
cuda_cuda_distributor_general_create  	 0.771   	 0.741   	 1.04
cuda_cuda_halo_fast_create  	 0.67   	 0.727   	 0.922
cuda_cuda_halo_fast_create  	 0.724   	 0.728   	 0.994
cuda_cuda_halo_fast_create  	 0.697   	 0.703   	 0.992
cuda_cuda_halo_fast_create  	 0.701   	 0.7   	 1
cuda_cuda_halo_fast_create  	 0.72   	 0.709   	 1.02
cuda_cuda_halo_fast_create  	 1.11   	 1.09   	 1.01
cuda_cuda_halo_general_create  	 0.657   	 0.711   	 0.924
cuda_cuda_halo_general_create  	 0.704   	 0.716   	 0.982
cuda_cuda_halo_general_create  	 0.681   	 0.688   	 0.99
cuda_cuda_halo_general_create  	 0.685   	 0.688   	 0.996
cuda_cuda_halo_general_create  	 0.706   	 0.697   	 1.01
cuda_cuda_halo_general_create  	 0.733   	 0.767   	 0.955
```

**Comment by streeve** [comment]
This is the fine grain timings for the updated `countSendsAndCreateSteeringShared` function: 

**Placeholder (needs averages and all sizes):**

1M particles with fraction communicated ( 0.0001 )
```
Prev(ms) 	New(ms) 	Speedup
0.837440     0.056896     14.7
```

**Comment by sslattery** [comment]
Would be good to see OpenMP timings as well.

**Comment by sslattery** [comment]
> Would be good to see OpenMP timings as well.
Wait doesn't matter - this is only updating the atomic code path.

**Review by sslattery — APPROVED** [review]

**Comment by streeve** [comment]
Updated timings and merging

**Pull request merged**
