### PR TITLE
Only run GitHub Actions on main repo

### PR DESCRIPTION
**Pull request by streeve**
Exclude forks from running CI

### CODE REVIEW

**Review by sslattery — COMMENTED** [review]
Does this improve our turnaround times?

**Comment by streeve** [comment]
> Does this improve our turnaround times?

Not sure. I just assumed we didn't need to run CI on forks

**Comment by junghans** [comment]
Why do you want to do that? Testing commits on a fork before making a PR seems like a reasonable use case.

**Comment by streeve** [comment]
> Why do you want to do that? Testing commits on a fork before making a PR seems like a reasonable use case.

Fair enough, I'll close

**Pull request closed without merging**
