### PR TITLE
CI: fix typo for sanitizer build

### PR DESCRIPTION
**Pull request by junghans**
Continuing #412

### CODE REVIEW

**Comment by streeve** [comment]
@junghans well I broke all of this, but should I disable on fedora or add asan to fedora ci-containers?

**Comment by junghans** [comment]
@streeve after https://github.com/ECP-copa/ci-containers/pull/7 is merged, will it work?

**Comment by streeve** [comment]
> @streeve after [ECP-copa/ci-containers#7](https://github.com/ECP-copa/ci-containers/pull/7) is merged, will it work?

It's still not finding `libasan` on fedora. But more of an issue is every MPI test failing with the LeakSanitizer - any ideas?

**Comment by junghans** [comment]
The rawhide containers wasn't updated, let's wait until next week and then try to publish it again.

**Comment by streeve** [comment]
@dalg24 can you take a quick look at this? The test for ArborX neighbor lists with a subset of particles is failing

**Comment by streeve** [comment]
retest this please.

**Comment by streeve** [comment]
@sslattery this is ready for final review - this only adds the address sanitizer and Damien pointed out my mistake for ArborX going out of bounds

**Review by sslattery — APPROVED** [review]

**Pull request merged**
