### PR TITLE
Removed value_type requirement for view functors in g2p vector gradient.

### PR DESCRIPTION
**Pull request by abisner**

### CODE REVIEW

**Comment by streeve** [comment]
Retest this please.

**Review by streeve — COMMENTED** [review]
`value_type` is still noted as required in a lot of comments - is that still the case?

**Comment by abisner** [comment]
The use of `ViewType::value_type` in the `G2P::` and `P2G::` methods was a holdover from an earlier revision, according to @sslattery. But it does not appear to be functionally necessary. It was only explicitly present in the 2D/3D vector gradient `G2P::` operators, and nowhere else (not for the scalar gradient, divergence, etc.)

**Review by streeve — APPROVED** [review]
Nice catch

**Review by sslattery — APPROVED** [review]

**Pull request merged**
