### PR TITLE
GHA: reenable doxygen upload

### PR DESCRIPTION
**Pull request by junghans**
Last item from #345

### CODE REVIEW

**Comment by streeve** [comment]
I think you need `doxygen: off` in the matrix

**Comment by junghans** [comment]
> I think you need `doxygen: off` in the matrix

It builds, there is a new build with "OFF, ON" at the end.

**Comment by streeve** [comment]
Yeah, I looked in the wrong place..

**Review by streeve — APPROVED** [review]

**Comment by junghans** [comment]
@streeve worked: https://ecp-copa.github.io/Cabana/doxygen/

**Pull request merged**
