### PR TITLE
Disable deprecated kokkos code

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
Wondering if this triggers the AMPI failures we see in #163

**Comment by dalg24** [comment]
Bingo

**Comment by dalg24** [comment]
@sslattery This PR is only establishing some relation with the failures with AMPI/Charm++ and the disabling deprecated code in Kokkos.  This is not ready for merge.

**Comment by sslattery** [comment]
Retest this PR once #171 is merged

**Pull request merged**
