### PR TITLE
CI: clean up

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@gotmax23 have you seen this before?
```
2021-09-24T02:06:28.1475575Z ##[command]/usr/bin/docker exec  ff01ada0d3472de3547ca4250f38a38487d665d3f2c9079ddeeeb98547a2e37a sh -c "cat /etc/*release | grep ^ID"
2021-09-24T02:06:28.4671782Z /__e/node12/bin/node[17]: ../src/node_platform.cc:63:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
2021-09-24T02:06:28.4738471Z  1: 0x9da7c0 node::Abort() [/__e/node12/bin/node]
2021-09-24T02:06:28.4738995Z  2: 0x9da847  [/__e/node12/bin/node]
2021-09-24T02:06:28.4739869Z  3: 0xa49c8a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/__e/node12/bin/node]
2021-09-24T02:06:28.4741028Z  4: 0xa49d4b node::NodePlatform::NodePlatform(int, node::tracing::TracingController*) [/__e/node12/bin/node]
2021-09-24T02:06:28.4741901Z  5: 0x94e3da node::InitializeV8Platform(int) [/__e/node12/bin/node]
2021-09-24T02:06:28.4742699Z  6: 0x9ac4c1 node::InitializeOncePerProcess(int, char**) [/__e/node12/bin/node]
2021-09-24T02:06:28.4743418Z  7: 0x9ac6b3 node::Start(int, char**) [/__e/node12/bin/node]
2021-09-24T02:06:28.4743909Z  8: 0x7f762e3e9540  [/lib64/libc.so.6]
2021-09-24T02:06:28.4744418Z  9: 0x7f762e3e95ec __libc_start_main [/lib64/libc.so.6]
2021-09-24T02:06:28.4744900Z 10: 0x94a055  [/__e/node12/bin/node]
2021-09-24T02:06:28.7092451Z Stop and remove container: 0ad28bcc178541cbba1e5aee73638320_espressoppbuildenvopensuse_1f1710
```
Only happened after using `ppa:pascallj/docker.io-clone3`.

**Comment by gotmax23** [comment]
I have not. I am not the most knowledgeable in this area, but maybe it has something to do with the way pascallj backported the fixes. If you are having problems with Docker and/or Buildx and are not using the multiarch features, the redhat-actions/buildah-build action might be a better solution

**Comment by junghans** [comment]
> I have not. I am not the most knowledgeable in this area, but maybe it has something to do with the way pascallj backported the fixes. If you are having problems with Docker and/or Buildx and are not using the multiarch features, the redhat-actions/buildah-build action might be a better solution

maybe @pascallj, knows, but the CI here is using a container (via `the container: ` tag) and the error even happens before the actual CI script runs.

**Comment by junghans** [comment]
@gotmax23 adding `options: --security-opt seccomp=unconfined` fixed it.

**Comment by pascallj** [comment]
If I'm interpreting the logs correctly, the error you are mentioning is on commit 6bdfa7c which doesn't include the change to my PPA. The CI on b702d29 also fails, but that has something to do with the systemctl command.

**Comment by junghans** [comment]
@streeve please review

@dalg24 Jenkins is out of disk space.

**Review by streeve — APPROVED** [review]

**Comment by junghans** [comment]
@pascallj yeah it seems CI containers-based on `fedora:rawhide` and `ubuntu:devel` cannot run `actions/cache` without `--security-opt seccomp=unconfined`, but we added that now to our CI, all good now.

**Comment by pascallj** [comment]
That's true. That's exactly the issue @gotmax23 referred to in the other issue/PR I was mentioned in. The issue is in the seccomp profiles, which is fixed in my PPA but is also fixed in Ubuntu Impish Proposed-Updates and hopefully soon in a released Docker version. Just verifying here that my PPA is not the cause of the error you described.

But disabling seccomp therefore also works. But note that although you can run containers with that option, you can't build them.

**Comment by junghans** [comment]
@pascallj yes your update is good.

**Comment by gotmax23** [comment]
@pascallj summed it up well. Unfortunately, the Docker version that the Github Actions runners use does not include the fix for that issue. As you alluded to, there is no way to change the Docker version when using the `container:` tag (it uses the version that's already available on the runner), so you are forced to use `options: --security-opt seccomp=unconfined` until a release of Docker with this fix comes out.

**Comment by streeve** [comment]
retest this please.

**Comment by streeve** [comment]
@junghans ready to merge?

**Comment by junghans** [comment]
Yes, go ahead!

**Pull request merged**
