### PR TITLE
Require MPI

### PR DESCRIPTION
**Pull request by sslattery**
Cajita requires MPI which means a large portion of the library will need MPI to function when it is merged. Would like thoughts/feedback here on the approach. Note that HIP is still disabled with MPI until #231 is resolved.

### CODE REVIEW

**Comment by sslattery** [comment]
> I am against requiring MPI

Can you elaborate on your objection?

**Comment by dalg24** [comment]
I feel like it is still reasonable to want to use Cabana w/o MPI.  We had discussed it at long before we implemented it this way.  We can just disable Cajita if MPI is not found for now and re-evaluate later if necessary.

**Comment by sslattery** [comment]
That is not unreasonable - should be easy to control the Cajita build. As a counter point I could see people wanting to use Cajita without MPI as well but that would require some signficant refactoring. As a result any Cajita+Cabana algorithms would require MPI as well. 

@rfbird @junghans thoughts?

**Comment by rfbird** [comment]
In an ideal world we would make it possible to build Cajita without MPI, but I've seen that's a none trivial code effort with minimal upside. I'm OK with No MPI => No Cajita.

**Comment by sslattery** [comment]
OK - we will proceed with the merger without an MPI requirement

**Pull request closed without merging**
