### PR TITLE
Move fortran tutorial

### PR DESCRIPTION
**Pull request by streeve**
Remove Fortran tutorial, moved here ECP-copa/Advanced-fortran-examples#4

Preferences on flattening `examples/tutorial/`?

I'll leave as draft until the accompanying PR is merged.

### CODE REVIEW

**Comment by sslattery** [comment]
retest this please

**Comment by sslattery** [comment]
@junghans have your requested changes been addressed?

**Comment by sslattery** [comment]
also FYI @juanecopro

**Comment by streeve** [comment]
@junghans This should be ready with ECP-copa/Cabana-fortran-examples#6 closed

**Pull request merged**
