### PR TITLE
Add HIP MPI

### PR DESCRIPTION
**Pull request by streeve**
Use the same strategy with HIP as CUDA. 

Worked with rocm/3.3 and openmpi/4.0.0 on MI25 at LLNL

### CODE REVIEW

**Comment by sslattery** [comment]
@dalg24 is MPI explicitly not included in the HIP Jenkins build stage?

**Comment by sslattery** [comment]
> @dalg24 is MPI explicitly not included in the HIP Jenkins build stage?

We are going to try adding it to the build stage and see what happens - @streeve has had some luck with it locally

**Comment by streeve** [comment]
Ok, this passed. The `MPIEXEC_MAX_NUMPROCS` is getting populated with what I assume is the CPU count, but otherwise it looks fine

**Comment by sslattery** [comment]
Looks like Jenkins passed - just not reporting the status

**Comment by dalg24** [comment]
> Looks like Jenkins passed - just not reporting the status

It did report success.

**Pull request merged**
