### PR TITLE
Add THREADS backend build to CI

### PR DESCRIPTION
**Pull request by streeve**
Renames backends in GHA to make this easier

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by streeve** [comment]
Needs fix: https://github.com/kokkos/kokkos/pull/5109 Once that's merged we can run with develop only

**Comment by dalg24** [comment]
How is it related to this CI build?

**Comment by streeve** [comment]
Our Threads failures are not just in CI, but any run with multiple threads with a `parallel_reduce`. @masterleinad mentioned a fix, but maybe I linked the wrong PR

**Comment by dalg24** [comment]
No that would be the one you are correct
But unless you have hwloc or specify the number of threads we were using only one thread

**Comment by masterleinad** [comment]
> Develop now works with my local build of core library only, but now Threads compilation fails for Cajita parallel reductions with tags

I'll have a look.

**Comment by masterleinad** [comment]
https://github.com/kokkos/kokkos/pull/5123 provides a fix.

**Comment by streeve** [comment]
Thanks, @masterleinad

**Pull request merged**
